/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hotel.reservation.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.math.BigDecimal;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Reservation service. Represents a row in the &quot;Reservation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.hotel.reservation.model.impl.ReservationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.hotel.reservation.model.impl.ReservationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Reservation
 * @generated
 */
@ProviderType
public interface ReservationModel extends BaseModel<Reservation>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a reservation model instance should use the {@link Reservation} interface instead.
	 */

	/**
	 * Returns the primary key of this reservation.
	 *
	 * @return the primary key of this reservation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this reservation.
	 *
	 * @param primaryKey the primary key of this reservation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the reservation ID of this reservation.
	 *
	 * @return the reservation ID of this reservation
	 */
	public long getReservationId();

	/**
	 * Sets the reservation ID of this reservation.
	 *
	 * @param reservationId the reservation ID of this reservation
	 */
	public void setReservationId(long reservationId);

	/**
	 * Returns the group ID of this reservation.
	 *
	 * @return the group ID of this reservation
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this reservation.
	 *
	 * @param groupId the group ID of this reservation
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this reservation.
	 *
	 * @return the company ID of this reservation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this reservation.
	 *
	 * @param companyId the company ID of this reservation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this reservation.
	 *
	 * @return the user ID of this reservation
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this reservation.
	 *
	 * @param userId the user ID of this reservation
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this reservation.
	 *
	 * @return the user uuid of this reservation
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this reservation.
	 *
	 * @param userUuid the user uuid of this reservation
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this reservation.
	 *
	 * @return the create date of this reservation
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this reservation.
	 *
	 * @param createDate the create date of this reservation
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this reservation.
	 *
	 * @return the modified date of this reservation
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this reservation.
	 *
	 * @param modifiedDate the modified date of this reservation
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the room ID of this reservation.
	 *
	 * @return the room ID of this reservation
	 */
	public long getRoomId();

	/**
	 * Sets the room ID of this reservation.
	 *
	 * @param roomId the room ID of this reservation
	 */
	public void setRoomId(long roomId);

	/**
	 * Returns the guest name of this reservation.
	 *
	 * @return the guest name of this reservation
	 */
	@AutoEscape
	public String getGuestName();

	/**
	 * Sets the guest name of this reservation.
	 *
	 * @param guestName the guest name of this reservation
	 */
	public void setGuestName(String guestName);

	/**
	 * Returns the guest email of this reservation.
	 *
	 * @return the guest email of this reservation
	 */
	@AutoEscape
	public String getGuestEmail();

	/**
	 * Sets the guest email of this reservation.
	 *
	 * @param guestEmail the guest email of this reservation
	 */
	public void setGuestEmail(String guestEmail);

	/**
	 * Returns the check in date of this reservation.
	 *
	 * @return the check in date of this reservation
	 */
	public Date getCheckInDate();

	/**
	 * Sets the check in date of this reservation.
	 *
	 * @param checkInDate the check in date of this reservation
	 */
	public void setCheckInDate(Date checkInDate);

	/**
	 * Returns the check out date of this reservation.
	 *
	 * @return the check out date of this reservation
	 */
	public Date getCheckOutDate();

	/**
	 * Sets the check out date of this reservation.
	 *
	 * @param checkOutDate the check out date of this reservation
	 */
	public void setCheckOutDate(Date checkOutDate);

	/**
	 * Returns the total amount of this reservation.
	 *
	 * @return the total amount of this reservation
	 */
	public BigDecimal getTotalAmount();

	/**
	 * Sets the total amount of this reservation.
	 *
	 * @param totalAmount the total amount of this reservation
	 */
	public void setTotalAmount(BigDecimal totalAmount);

	/**
	 * Returns the status of this reservation.
	 *
	 * @return the status of this reservation
	 */
	public int getStatus();

	/**
	 * Sets the status of this reservation.
	 *
	 * @param status the status of this reservation
	 */
	public void setStatus(int status);

	@Override
	public Reservation cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}