/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hotel.reservation.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.math.BigDecimal;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Room service. Represents a row in the &quot;Room&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.hotel.reservation.model.impl.RoomModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.hotel.reservation.model.impl.RoomImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Room
 * @generated
 */
@ProviderType
public interface RoomModel extends BaseModel<Room>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a room model instance should use the {@link Room} interface instead.
	 */

	/**
	 * Returns the primary key of this room.
	 *
	 * @return the primary key of this room
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this room.
	 *
	 * @param primaryKey the primary key of this room
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the room ID of this room.
	 *
	 * @return the room ID of this room
	 */
	public long getRoomId();

	/**
	 * Sets the room ID of this room.
	 *
	 * @param roomId the room ID of this room
	 */
	public void setRoomId(long roomId);

	/**
	 * Returns the group ID of this room.
	 *
	 * @return the group ID of this room
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this room.
	 *
	 * @param groupId the group ID of this room
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this room.
	 *
	 * @return the company ID of this room
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this room.
	 *
	 * @param companyId the company ID of this room
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this room.
	 *
	 * @return the user ID of this room
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this room.
	 *
	 * @param userId the user ID of this room
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this room.
	 *
	 * @return the user uuid of this room
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this room.
	 *
	 * @param userUuid the user uuid of this room
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this room.
	 *
	 * @return the create date of this room
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this room.
	 *
	 * @param createDate the create date of this room
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this room.
	 *
	 * @return the modified date of this room
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this room.
	 *
	 * @param modifiedDate the modified date of this room
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this room.
	 *
	 * @return the name of this room
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this room.
	 *
	 * @param name the name of this room
	 */
	public void setName(String name);

	/**
	 * Returns the description of this room.
	 *
	 * @return the description of this room
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this room.
	 *
	 * @param description the description of this room
	 */
	public void setDescription(String description);

	/**
	 * Returns the image file entry ID of this room.
	 *
	 * @return the image file entry ID of this room
	 */
	public long getImageFileEntryId();

	/**
	 * Sets the image file entry ID of this room.
	 *
	 * @param ImageFileEntryId the image file entry ID of this room
	 */
	public void setImageFileEntryId(long ImageFileEntryId);

	/**
	 * Returns the max guests of this room.
	 *
	 * @return the max guests of this room
	 */
	public int getMaxGuests();

	/**
	 * Sets the max guests of this room.
	 *
	 * @param maxGuests the max guests of this room
	 */
	public void setMaxGuests(int maxGuests);

	/**
	 * Returns the daily rate of this room.
	 *
	 * @return the daily rate of this room
	 */
	public BigDecimal getDailyRate();

	/**
	 * Sets the daily rate of this room.
	 *
	 * @param dailyRate the daily rate of this room
	 */
	public void setDailyRate(BigDecimal dailyRate);

	/**
	 * Returns the amenities of this room.
	 *
	 * @return the amenities of this room
	 */
	@AutoEscape
	public String getAmenities();

	/**
	 * Sets the amenities of this room.
	 *
	 * @param amenities the amenities of this room
	 */
	public void setAmenities(String amenities);

	/**
	 * Returns the status of this room.
	 *
	 * @return the status of this room
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this room is status.
	 *
	 * @return <code>true</code> if this room is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this room is status.
	 *
	 * @param status the status of this room
	 */
	public void setStatus(boolean status);

	@Override
	public Room cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}