/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hotel.reservation.model.impl;

import com.hotel.reservation.model.Reservation;
import com.hotel.reservation.service.ReservationLocalServiceUtil;

/**
 * The extended model base implementation for the Reservation service. Represents a row in the &quot;Reservation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReservationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReservationImpl
 * @see Reservation
 * @generated
 */
public abstract class ReservationBaseImpl
	extends ReservationModelImpl implements Reservation {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a reservation model instance should use the <code>Reservation</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ReservationLocalServiceUtil.addReservation(this);
		}
		else {
			ReservationLocalServiceUtil.updateReservation(this);
		}
	}

}